### ISSUE TITLE
Update functionality 

### ISSUE THREAD

**Issue by radojesrb** [zinserjan/wdio-visual-regression-service#53] opened 2017-10-16 13:58 UTC
Hi,

correct me if I am wrong, but it looks like there is no built in logic for updating the state of the tests.
Let's say that I have intentional change in the UI which breaks the test. And I want to be able to update the /reference directory so that tests are not failing.

I know that it can be easily done manually, but that is not what I want.
Also, I can write my own logic to achieve that but that is as well not first choice.

**Let's try to determine together what "update" of the current state means:**
1. copy the content of /screen (overwrite) the content of /reference
2. remove the /diff
3. run the test again

Do you agree with this? Since, that way test will generate new /reference on next run, thus it will not fail and intentional change will be applied as new state.

I would rather make this as upgrade to the library and init PR than to make my own code which works outside of it.

Thanks!

**Comment by zinserjan** [comment] 2017-10-25 15:50
I think this is a duplicate of #17? You can already achieve this functionality with the [save screenshot method](https://github.com/zinserjan/wdio-visual-regression-service#visualregressioncomparesavescreenshot).

**Closed** 2018-03-22 10:46 UTC
